"""
Generate the v2 provenance viewer HTML with embedded data.

This creates a self-contained HTML file that works with file:// URLs.
"""
import json
from pathlib import Path

def main():
    # Read the v2 provenance data
    data_file = Path('data/analysis/v2_provenance_database.json')
    if not data_file.exists():
        print("Error: Run generate_v2_provenance.py first")
        return

    with open(data_file) as f:
        data = json.load(f)

    print(f"Loaded {data['statistics']['total']} books")
    print(f"  Complete: {data['statistics']['complete']}")
    print(f"  Missing: {data['statistics']['missing']}")

    # Read the viewer template
    viewer_template = Path('web/viewers/v2_provenance_viewer.html')
    with open(viewer_template) as f:
        html = f.read()

    # Replace the fetch-based loading with embedded data
    # Find and replace the loadData function
    old_load = '''async function loadData() {
            try {
                document.getElementById('loading').style.display = 'block';
                document.getElementById('songbooks-table').style.display = 'none';

                const response = await fetch('../../data/analysis/v2_provenance_database.json');
                const data = await response.json();
                provenanceData = data;
                filteredData = data.songbooks;

                updateStats(data.statistics, data.songbooks);
                renderTable();

                document.getElementById('loading').style.display = 'none';
                document.getElementById('songbooks-table').style.display = 'table';

                // Add filter event listeners
                document.getElementById('search').addEventListener('input', applyFilters);
                document.getElementById('filter-status').addEventListener('change', applyFilters);

            } catch (error) {
                document.getElementById('loading').innerHTML =
                    '<span style="color: #f44336;">Error loading data. Run: py scripts/analysis/generate_v2_provenance.py</span>';
            }
        }'''

    # Create embedded data version
    embedded_data_json = json.dumps(data)

    new_load = f'''// Embedded data (generated by generate_v2_viewer.py)
        const embeddedData = {embedded_data_json};

        async function loadData() {{
            document.getElementById('loading').style.display = 'block';
            document.getElementById('songbooks-table').style.display = 'none';

            provenanceData = embeddedData;
            filteredData = embeddedData.songbooks;

            updateStats(embeddedData.statistics, embeddedData.songbooks);
            renderTable();

            document.getElementById('loading').style.display = 'none';
            document.getElementById('songbooks-table').style.display = 'table';

            // Add filter event listeners
            document.getElementById('search').addEventListener('input', applyFilters);
            document.getElementById('filter-status').addEventListener('change', applyFilters);
        }}'''

    html = html.replace(old_load, new_load)

    # Update title with count
    html = html.replace(
        '<title>V2 Pipeline Provenance Viewer</title>',
        f'<title>V2 Pipeline Provenance - {data["statistics"]["complete"]} Complete / {data["statistics"]["total"]} Total</title>'
    )

    # Write the output
    output_file = Path('web/viewers/v2_provenance_viewer_embedded.html')
    with open(output_file, 'w') as f:
        f.write(html)

    print(f"\nGenerated: {output_file}")
    print(f"Open in browser: file:///{output_file.resolve()}")


if __name__ == '__main__':
    main()
